test: test reproducing the issue 1535
This is the panic we see when using serde_yml for this specific case:

```
failures:
    sbom::issue_1535::not_really_clearly_defined

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 68
    filtered out; finished in 4.51s

    ──── STDERR:             trustify-module-fundamental::fundamental
    sbom::issue_1535::not_really_clearly_defined

    thread 'sbom::issue_1535::not_really_clearly_defined' panicked at
    /home/heliofrota/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f
    /libyml-0.0.5/src/scanner.rs:2798:17:
    String join would overflow memory bounds
    note: run with `RUST_BACKTRACE=1` environment variable to display
    a backtrace

      Cancelling due to test failure
      ────────────
           Summary [   4.526s] 1 test run: 0 passed, 1 failed, 422
           skipped
                   FAIL [   4.517s]
                   trustify-module-fundamental::fundamental
                   sbom::issue_1535::not_really_clearly_defined
                   error: test run failed
                   ➜  trustify git:(test) ✗
```